### ISSUE TITLE
RestartActorException

### ISSUE THREAD

**Issue by jhegedus42** [tudorzgureanu/akka-persistence-playground#1]
Any idea why I get the exception below ?

```

Testing started at 17.52 ...
[INFO] [05/03/2017 17:52:08.830] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-3] [akka://ShoppingCartActorSpec2/user/$a] Recovery completed!
[WARN] [05/03/2017 17:52:08.870] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-2] [akka.serialization.Serialization(akka://ShoppingCartActorSpec2)] Using the default Java serializer for class [com.ted.playground.akka.persistence.shopping.ShoppingCartActor$ItemAdded] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
[ERROR] [05/03/2017 17:52:09.100] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-3] [akka://ShoppingCartActorSpec2/user/$a] null
com.ted.playground.akka.persistence.fixtures.RestartableActor$RestartActorException$
	at com.ted.playground.akka.persistence.fixtures.RestartableActor$RestartActorException$.<clinit>(RestartableActor.scala)
	at com.ted.playground.akka.persistence.fixtures.RestartableActor$$anonfun$receiveCommand$1.applyOrElse(RestartableActor.scala:9)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at com.ted.playground.akka.persistence.shopping.ShoppingCartActor.akka$persistence$Eventsourced$$super$aroundReceive(ShoppingCartActor.scala:30)
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:657)
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:182)
	at com.ted.playground.akka.persistence.shopping.ShoppingCartActor.aroundReceive(ShoppingCartActor.scala:30)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [05/03/2017 17:52:09.183] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-2] [akka://ShoppingCartActorSpec2/user/$a] Recovery completed!
[WARN] [05/03/2017 17:52:09.216] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-4] [akka.serialization.Serialization(akka://ShoppingCartActorSpec2)] Using the default Java serializer for class [com.ted.playground.akka.persistence.shopping.ShoppingCartActor$ItemUpdated] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
[ERROR] [05/03/2017 17:52:09.222] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-2] [akka://ShoppingCartActorSpec2/user/$b] null
com.ted.playground.akka.persistence.fixtures.RestartableActor$RestartActorException$
	at com.ted.playground.akka.persistence.fixtures.RestartableActor$RestartActorException$.<clinit>(RestartableActor.scala)
	at com.ted.playground.akka.persistence.fixtures.RestartableActor$$anonfun$receiveCommand$1.applyOrElse(RestartableActor.scala:9)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at com.ted.playground.akka.persistence.shopping.ShoppingCartActor.akka$persistence$Eventsourced$$super$aroundReceive(ShoppingCartActor.scala:30)
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:657)
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:182)
	at com.ted.playground.akka.persistence.shopping.ShoppingCartActor.aroundReceive(ShoppingCartActor.scala:30)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [05/03/2017 17:52:09.235] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-7] [akka://ShoppingCartActorSpec2/user/$b] Recovery completed!
[INFO] [05/03/2017 17:52:09.242] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-2] [akka://ShoppingCartActorSpec2/user/$c] Recovery completed!
[WARN] [05/03/2017 17:52:09.256] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-2] [akka.serialization.Serialization(akka://ShoppingCartActorSpec2)] Using the default Java serializer for class [com.ted.playground.akka.persistence.shopping.ShoppingCartActor$ItemRemoved] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
[ERROR] [05/03/2017 17:52:09.260] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-2] [akka://ShoppingCartActorSpec2/user/$c] null
com.ted.playground.akka.persistence.fixtures.RestartableActor$RestartActorException$
	at com.ted.playground.akka.persistence.fixtures.RestartableActor$RestartActorException$.<clinit>(RestartableActor.scala)
	at com.ted.playground.akka.persistence.fixtures.RestartableActor$$anonfun$receiveCommand$1.applyOrElse(RestartableActor.scala:9)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at com.ted.playground.akka.persistence.shopping.ShoppingCartActor.akka$persistence$Eventsourced$$super$aroundReceive(ShoppingCartActor.scala:30)
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:657)
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:182)
	at com.ted.playground.akka.persistence.shopping.ShoppingCartActor.aroundReceive(ShoppingCartActor.scala:30)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [05/03/2017 17:52:09.272] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-2] [akka://ShoppingCartActorSpec2/user/$c] Recovery completed!
[INFO] [05/03/2017 17:52:09.200] [ShoppingCartActorSpec2-akka.actor.default-dispatcher-2] [akka://ShoppingCartActorSpec2/user/$b] Recovery completed!

Process finished with exit code 0K
```

**Comment by jhegedus42** [comment]
ahhh...ok it's part of the issue :) - i think i need to have a walk ....
